### ISSUE TITLE
Breaking on React 16 - PropTypes

### ISSUE THREAD

**Issue by sp4cecat** [noentiger/react-app-flexbox-grid#1]
# Issue summary

Compilation is breaking because of reliance on core React PropTypes, which has been completely removed from React 16.

react flexbox grid has upgraded - copying lib directory from react-flexbox-grid to react-app-flexbox-grid fixes the issue ..

## Expected behavior
Trouble-free compilation

## Actual behavior

```
TypeError: Cannot read property 'oneOfType' of undefined

Object../node_modules/react-app-flexbox-grid/lib/types.js
node_modules/react-app-flexbox-grid/lib/types.js:8
```

## Steps to Reproduce the Problem

1. `import {Grid, Row, Col} from "react-app-flexbox-grid"`
1. Try to build.

## Specifications

- Polaris version:
- React version: 16
- Browser: Chrome
- Device: Desktop
- Operating System: OSX

**Comment by noentiger** [comment]
@sp4cecat Thanks for noticing this issue. I have now updated this package to work with React 16 but since [react-flexbox-grid](https://github.com/roylee0704/react-flexbox-grid) works flawless with `create-react-app` at the moment I recommend you to use that library, since this library now is officially deprecated.

**Comment by noentiger** [comment]
I will now close this issue and refer to this [commit](https://github.com/noentiger/react-app-flexbox-grid/commit/d358c1585d73bcd44707f8e1c2382d04f3577324)
